# Generated by Django 3.2.4 on 2021-06-22 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodePostal',
            fields=[
                ('codePostal_name', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Code Postal')),
            ],
            options={
                'verbose_name': 'Code Postal',
                'verbose_name_plural': 'Code Postaux',
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('pays_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Pays')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Villes',
            fields=[
                ('ville_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Ville')),
                ('cp_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RESTAURANTS.codepostal')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nom du restaurant')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Email')),
                ('adress', models.CharField(max_length=200, verbose_name='Adresse du restaurant')),
                ('phone', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de téléphone')),
                ('webSite', models.URLField(blank=True, verbose_name='Site web')),
                ('image', models.URLField(verbose_name="Lien de l'image")),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RESTAURANTS.villes')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RESTAURANTS.pays')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
    ]
