# Generated by Django 3.1.3 on 2021-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nom du restaurant')),
                ('email', models.EmailField(blank=True, max_length=150, verbose_name='Email')),
                ('adress', models.CharField(max_length=200, verbose_name='Adresse du restaurant')),
                ('codePostal', models.BigIntegerField(default=75000, verbose_name='Code Postal')),
                ('city', models.CharField(default='Paris', max_length=200, verbose_name='Ville')),
                ('phoneIndicator', models.PositiveIntegerField(blank=True, verbose_name='Indicateur du Pays')),
                ('phone', models.CharField(blank=True, max_length=15, unique=True, verbose_name='Numéro de téléphone')),
                ('webSite', models.URLField(blank=True, verbose_name='Site web')),
                ('image', models.ImageField(upload_to='G:\\PROGRAMMATION\\SITES_WEB\\DIAS_OMONTE\\static/MEDIAS/restaurants/')),
            ],
        ),
    ]
