# Generated by Django 3.1.3 on 2021-06-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Catégorie du Logiciel')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('developer_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Auteur du Logiciel')),
                ('developer_web_site', models.URLField(blank=True, verbose_name='Site web du créateur du Logiciel')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Licence')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('software_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Nom du Logiciel')),
                ('software_logo', models.URLField(verbose_name='Logo du Logiciel')),
                ('software_description', models.TextField(blank=True, verbose_name='Description')),
                ('software_image', models.URLField(verbose_name='Image du Logiciel')),
                ('software_version', models.CharField(blank=True, max_length=20, verbose_name='Version du Logiciel')),
                ('software_source', models.URLField(verbose_name='Source du Logiciel')),
                ('software_download_size', models.CharField(blank=True, max_length=15, verbose_name='Taille du fichier téléchargé')),
                ('software_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SOFTWARE_LIBRARY.category')),
                ('software_developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SOFTWARE_LIBRARY.developer')),
                ('software_license', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SOFTWARE_LIBRARY.license')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
            },
        ),
    ]
