# Generated by Django 3.1.3 on 2021-06-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOFTWARE_LIBRARY', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Developpeur', 'verbose_name_plural': 'Developpeurs'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Licence', 'verbose_name_plural': 'Licences'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Logiciel', 'verbose_name_plural': 'Logiciels'},
        ),
    ]
